"""initial

Revision ID: 09cad76741ff
Revises: 
Create Date: 2026-06-22 20:57:39.735922

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '09cad76741ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
